/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coffee.machine;

import coffee.machine.termui.ResponseWriter;

import java.io.InputStreamReader;

import static coffee.machine.termui.CommandParser.arguments;
import static coffee.machine.termui.CommandParser.command;

public class Main {

    public static void main(String[] args) {
        ResponseWriter responseWriter = new ResponseWriter(System.out, System.err);

        Application.builder()
                .with(new InputStreamReader(System.in))
                .with(responseWriter)
                .add(command("init", "initialize a coffee machine",
                        arguments("slots", "total number of slots")), null)
                .add(command("info", "show coffee machine info"), null)
                .add(command("list-recipes", "list available recipes"), null)
                .add(command("make-coffee", "make coffee",
                        arguments("slot", "slot to use", "recipe", "coffee recipe")), null)
                .add(command("fill-ingredient", "refil ingredient",
                        arguments("name", "ingredient name", "quantity", "quantity")), null)
                .build()
                .start();

    }
}
